import type { CSSProperties } from 'react';
import {
  avatarBase,
  iconButtonBase,
  pageSubtitle,
  pageTitle,
  primaryButtonBase,
  surfaceCard,
  topActionsBase,
  topbarBase,
  uiTheme,
} from '../theme/commonStyles';

export const appTopbarStyles: Record<string, CSSProperties> = {
  topbar: { ...topbarBase, position: 'relative' },
  topActions: topActionsBase,
  title: pageTitle,
  subtitle: pageSubtitle,
  eyebrow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    color: uiTheme.colors.muted,
    fontSize: 13,
    fontWeight: 500,
  },
  menuRoot: {
    position: 'relative',
  },
  bell: {
    ...iconButtonBase,
    position: 'relative',
    transition:
      'transform 160ms ease, box-shadow 160ms ease, border-color 160ms ease',
  },
  bellBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    background: uiTheme.colors.danger,
    color: '#fff',
    borderRadius: 999,
    minWidth: 18,
    height: 18,
    display: 'grid',
    placeItems: 'center',
    fontSize: 10,
    padding: '0 5px',
    boxSizing: 'border-box',
    fontWeight: 700,
  },
  avatarButton: {
    ...avatarBase,
    width: 38,
    height: 38,
    border: 'none',
    cursor: 'pointer',
    fontSize: 13,
  },
  userButton: {
    border: `1px solid ${uiTheme.colors.border}`,
    background: 'var(--control-bg)',
    color: uiTheme.colors.text,
    borderRadius: 16,
    minHeight: 46,
    padding: '5px 8px 5px 6px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    boxShadow: uiTheme.shadows.card,
    transition:
      'transform 160ms ease, box-shadow 160ms ease, border-color 160ms ease',
  },
  userAvatar: {
    ...avatarBase,
    width: 34,
    height: 34,
    fontSize: 12,
    flexShrink: 0,
  },
  userCopy: {
    display: 'grid',
    textAlign: 'left',
    gap: 2,
    minWidth: 0,
  },
  userName: {
    fontSize: 13,
    lineHeight: 1.1,
  },
  userRole: {
    color: uiTheme.colors.muted,
    fontSize: 11,
    lineHeight: 1.1,
  },
  searchField: {
    minWidth: 220,
    height: 40,
    display: 'grid',
    gridTemplateColumns: '34px 1fr',
    alignItems: 'center',
    border: `1px solid ${uiTheme.colors.borderStrong}`,
    borderRadius: 16,
    background: 'var(--control-bg)',
    overflow: 'hidden',
    boxShadow: uiTheme.shadows.card,
  },
  searchIcon: {
    display: 'grid',
    placeItems: 'center',
    color: uiTheme.colors.muted,
  },
  searchInput: {
    border: 0,
    outline: 'none',
    background: 'transparent',
    color: uiTheme.colors.text,
    fontSize: 13,
    fontFamily: 'inherit',
    padding: '0 14px 0 0',
  },
  primaryButton: {
    ...primaryButtonBase,
    textDecoration: 'none',
    padding: '0 16px',
    minHeight: 40,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    cursor: 'pointer',
    fontSize: 14,
    borderRadius: 14,
    transition: 'transform 160ms ease, box-shadow 160ms ease, filter 160ms ease',
  },
  dropdown: {
    ...surfaceCard,
    position: 'absolute',
    top: 46,
    right: 0,
    zIndex: 40,
    width: 360,
    padding: 8,
    display: 'grid',
    gap: 4,
    borderRadius: 18,
    boxShadow: '0 20px 48px rgba(15, 23, 42, 0.14)',
  },
  dropdownHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '8px 10px 10px',
    fontSize: 13,
  },
  dropdownLink: {
    color: uiTheme.colors.primary,
    textDecoration: 'none',
    fontSize: 12,
    fontWeight: 600,
  },
  markAllButton: {
    border: 0,
    background: 'transparent',
    color: uiTheme.colors.primary,
    fontWeight: 700,
    fontSize: 12,
    textAlign: 'left',
    padding: '4px 10px 8px',
    cursor: 'pointer',
  },
  alertItem: {
    width: '100%',
    border: 0,
    background: 'transparent',
    display: 'grid',
    gridTemplateColumns: '30px 1fr 8px',
    gap: 10,
    alignItems: 'center',
    padding: '10px',
    borderRadius: 14,
    textDecoration: 'none',
    color: uiTheme.colors.text,
    cursor: 'pointer',
    textAlign: 'left',
  },
  alertItemUnread: {
    background: uiTheme.colors.primarySoft,
  },
  alertCopy: {
    display: 'grid',
    gap: 3,
    minWidth: 0,
  },
  alertIconDanger: {
    width: 30,
    height: 30,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  alertIconSuccess: {
    width: 30,
    height: 30,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    background: uiTheme.colors.primary,
  },
  emptyState: {
    padding: 18,
    color: uiTheme.colors.muted,
    fontSize: 13,
    textAlign: 'center',
  },
  userDropdown: {
    ...surfaceCard,
    position: 'absolute',
    top: 46,
    right: 0,
    zIndex: 40,
    width: 190,
    padding: 6,
    display: 'grid',
    gap: 4,
    borderRadius: 18,
    boxShadow: '0 20px 48px rgba(15, 23, 42, 0.14)',
  },
  userMenuItem: {
    border: 0,
    background: 'transparent',
    color: uiTheme.colors.text,
    minHeight: 36,
    padding: '0 10px',
    borderRadius: 14,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    fontSize: 12,
    fontWeight: 500,
    textAlign: 'left',
    textDecoration: 'none',
  },
  toast: {
    ...surfaceCard,
    position: 'fixed',
    right: 24,
    bottom: 24,
    zIndex: 100,
    width: 330,
    border: 0,
    display: 'grid',
    gridTemplateColumns: '34px 1fr',
    gap: 12,
    alignItems: 'center',
    padding: 14,
    cursor: 'pointer',
    textAlign: 'left',
    color: uiTheme.colors.text,
    boxShadow: '0 20px 48px rgba(15, 23, 42, 0.14)',
  },
  toastIconDanger: {
    width: 34,
    height: 34,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  toastIconSuccess: {
    width: 34,
    height: 34,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
};
