import type { CSSProperties } from 'react';
import {
  controlBase,
  inputBase,
  pageActiveButtonBase,
  pageArrowBase,
  pageMain,
  secondaryButtonBase,
  surfaceCard,
  uiTheme,
} from '../../theme/commonStyles';

export const styles: Record<string, CSSProperties> = {
  page: {
    ...pageMain,
    display: "flex",
    flexDirection: "column",
    gap: 22,
    backgroundImage:
      "linear-gradient(135deg, rgba(37, 99, 235, 0.07), transparent 30%), linear-gradient(225deg, rgba(15, 23, 42, 0.045), transparent 28%)",
  },
  feedbackInfo: {
    ...surfaceCard,
    padding: "14px 18px",
    color: uiTheme.colors.primary,
    background: uiTheme.colors.primarySoft,
    borderColor: uiTheme.colors.primarySoft,
    fontWeight: 600,
  },
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: uiTheme.colors.muted,
    fontSize: 13,
    fontWeight: 500,
  },
  breadcrumbLink: {
    color: uiTheme.colors.muted,
    textDecoration: "none",
  },
  hero: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 24,
  },
  heroMain: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    minWidth: 0,
  },
  heroIcon: {
    width: 84,
    height: 84,
    borderRadius: 20,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  },
  heroCopy: {
    minWidth: 0,
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  title: {
    margin: 0,
    fontSize: 28,
    lineHeight: 1.1,
    fontWeight: 850,
    color: uiTheme.colors.text,
    letterSpacing: "0em",
  },
  countBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "6px 10px",
    borderRadius: 999,
    color: uiTheme.colors.primary,
    background: uiTheme.colors.primarySoft,
    fontSize: 12,
    fontWeight: 600,
  },
  description: {
    margin: "10px 0 0",
    color: uiTheme.colors.muted,
    maxWidth: 680,
  },
  metaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 16,
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 500,
  },
  metaItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  metaDivider: {
    width: 1,
    height: 15,
    background: uiTheme.colors.borderStrong,
  },
  heroActions: {
    position: "relative",
    display: "flex",
    justifyContent: "flex-end",
  },
  primaryButton: {
    ...controlBase,
    minHeight: 40,
    padding: "0 16px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    borderRadius: 12,
    borderColor: uiTheme.colors.primary,
    background: uiTheme.colors.primary,
    color: "#fff",
    fontWeight: 700,
  },
  secondaryLink: {
    ...secondaryButtonBase,
    marginTop: 16,
    minHeight: 40,
    padding: "0 14px",
    display: "inline-flex",
    alignItems: "center",
    textDecoration: "none",
    fontWeight: 500,
    borderRadius: 14,
  },
  secondaryButton: {
    ...secondaryButtonBase,
    minHeight: 38,
    padding: "0 14px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    cursor: "pointer",
    fontWeight: 500,
    textDecoration: "none",
    borderRadius: 12,
  },
  moreButton: {
    ...controlBase,
    width: 42,
    height: 42,
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  menu: {
    ...surfaceCard,
    position: "absolute",
    top: 48,
    right: 0,
    minWidth: 220,
    zIndex: 10,
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    borderRadius: 18,
  },
  menuItem: {
    border: "none",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 10,
    borderRadius: 10,
    padding: "10px 12px",
    color: uiTheme.colors.text,
    cursor: "pointer",
    fontWeight: 600,
    textAlign: "left",
  },
  menuItemDisabled: {
    color: uiTheme.colors.muted,
    cursor: "not-allowed",
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 14,
  },
  exportCard: {
    ...surfaceCard,
    borderRadius: 20,
    padding: 18,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  exportTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 700,
  },
  exportSubtitle: {
    margin: "6px 0 0",
    color: uiTheme.colors.muted,
    fontSize: 12,
    maxWidth: 640,
  },
  exportControls: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    flexWrap: "wrap",
  },
  exportSelect: {
    ...inputBase,
    minHeight: 40,
    borderRadius: 12,
    minWidth: 170,
  },
  kpiCard: {
    ...surfaceCard,
    minHeight: 92,
    padding: 18,
    display: "flex",
    alignItems: "center",
    gap: 16,
    borderRadius: 20,
  },
  kpiIcon: {
    width: 50,
    height: 50,
    borderRadius: 16,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  },
  kpiIcongreen: {
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  kpiIconblue: {
    color: uiTheme.colors.primary,
    background: uiTheme.colors.primarySoft,
  },
  kpiIconorange: {
    color: uiTheme.colors.warning,
    background: uiTheme.colors.warningSoft,
  },
  kpiIconpurple: {
    color: uiTheme.colors.primaryDark,
    background: uiTheme.colors.surfaceSoft,
  },
  alertDot: {
    width: 16,
    height: 16,
    borderRadius: 999,
    background: uiTheme.colors.warning,
  },
  kpiTitle: {
    display: "block",
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 500,
    marginBottom: 6,
  },
  kpiValue: {
    display: "block",
    color: uiTheme.colors.text,
    fontSize: 22,
    lineHeight: 1.1,
  },
  kpiNote: {
    margin: "8px 0 0",
    color: uiTheme.colors.muted,
    fontSize: 12,
  },
  valueGreen: {
    color: uiTheme.colors.success,
  },
  valueOrange: {
    color: uiTheme.colors.warning,
  },
  valueSlate: {
    color: uiTheme.colors.muted,
  },
  tabs: {
    display: "flex",
    gap: 12,
    borderBottom: `1px solid ${uiTheme.colors.border}`,
  },
  tabButton: {
    border: "none",
    background: "transparent",
    color: uiTheme.colors.muted,
    fontWeight: 500,
    fontSize: 14,
    padding: "0 16px 14px",
    cursor: "pointer",
  },
  tabActiveButton: {
    border: "none",
    background: "transparent",
    color: uiTheme.colors.primary,
    fontWeight: 600,
    fontSize: 14,
    padding: "0 16px 14px",
    cursor: "pointer",
    boxShadow: `inset 0 -2px 0 ${uiTheme.colors.primary}`,
  },
  tdActions: {
    padding: "14px 16px",
    color: uiTheme.colors.text,
    fontSize: 13,
    overflow: "visible",
    whiteSpace: "nowrap",
    textAlign: "right",
  },

  rowActionButton: {
    ...controlBase,
    width: 38,
    height: 38,
    minWidth: 38,
    padding: 0,
    display: "inline-grid",
    placeItems: "center",
    cursor: "pointer",
    borderRadius: 12,
    background: uiTheme.colors.surface,
    color: uiTheme.colors.muted,
  },
  monitorArea: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    minWidth: 0,
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  searchWrap: {
    ...inputBase,
    width: "min(360px, 100%)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: uiTheme.colors.muted,
    paddingLeft: 14,
    borderRadius: 14,
  },
  searchInput: {
    border: "none",
    outline: "none",
    width: "100%",
    background: "transparent",
    color: uiTheme.colors.text,
    fontSize: 14,
  },
  filters: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  selectWrap: {
    ...controlBase,
    height: 42,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "0 14px",
    color: uiTheme.colors.muted,
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 14,
  },
  select: {
    border: "none",
    background: "transparent",
    outline: "none",
    color: uiTheme.colors.text,
    fontWeight: 500,
  },
  filterButton: {
    ...controlBase,
    width: 42,
    height: 42,
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
    color: uiTheme.colors.muted,
    borderRadius: 14,
  },
  tableCard: {
    ...surfaceCard,
    overflow: "hidden",
    borderRadius: 20,
  },
  table: {
    width: "100%",
    minWidth: 980,
    tableLayout: "fixed",
    borderCollapse: "separate",
    borderSpacing: 0,
  },
  th: {
    textAlign: "left",
    padding: "13px 16px",
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 600,
    background: uiTheme.colors.surfaceSoft,
    borderBottom: `1px solid ${uiTheme.colors.border}`,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tr: {
    cursor: "pointer",
    borderBottom: `1px solid ${uiTheme.colors.border}`,
    background: uiTheme.colors.surface,
  },
  td: {
    padding: "14px 16px",
    color: uiTheme.colors.text,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  monitorCell: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  monitorIcon: {
    width: 38,
    height: 38,
    minWidth: 38,
    flexShrink: 0,
    borderRadius: 9,
    display: "grid",
    placeItems: "center",
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  monitorCopy: {
    display: "grid",
    gap: 4,
    minWidth: 0,
    overflow: "hidden",
  },
  typeBadge: {
    display: "inline-flex",
    padding: "5px 8px",
    borderRadius: 7,
    color: uiTheme.colors.primary,
    background: uiTheme.colors.primarySoft,
    fontWeight: 600,
    fontSize: 12,
  },
  customBadge: {
    display: "inline-flex",
    padding: "5px 8px",
    borderRadius: 7,
    color: uiTheme.colors.warning,
    background: uiTheme.colors.warningSoft,
    fontWeight: 600,
    fontSize: 12,
  },
  scheduleText: {
    color: uiTheme.colors.muted,
    fontWeight: 600,
  },
  statusText: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 500,
  },
  statusDot: {
    fontSize: 12,
    lineHeight: 1,
  },
  statusGreen: {
    color: uiTheme.colors.success,
  },
  statusOrange: {
    color: uiTheme.colors.warning,
  },
  statusSlate: {
    color: uiTheme.colors.muted,
  },
  uptimeCell: {
    display: "inline-flex",
    alignItems: "center",
    gap: 14,
    fontWeight: 600,
  },
  uptimeTrend: {
    color: uiTheme.colors.success,
    fontWeight: 600,
  },
  pagination: {
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  paginationText: {
    fontSize: 13,
  },
  pages: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pageArrow: {
    ...pageArrowBase,
  },
  pageArrowLeft: {
    display: "inline-flex",
    transform: "rotate(180deg)",
  },
  pageActiveButton: {
    ...pageActiveButtonBase,
  },
  pageNumberButton: {
    ...pageArrowBase,
    width: 36,
    fontWeight: 500,
  },
  pageSize: {
    justifySelf: "end",
    ...controlBase,
    padding: "8px 12px",
  },
  emptyState: {
    minHeight: 420,
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    color: uiTheme.colors.text,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 18,
    margin: "0 auto 16px",
    display: "grid",
    placeItems: "center",
    background: uiTheme.colors.primarySoft,
    color: uiTheme.colors.primary,
  },
  emptyTable: {
    minHeight: 240,
    display: "grid",
    placeItems: "center",
    color: uiTheme.colors.muted,
  },
  memberList: {
    display: "grid",
    gap: 0,
  },
  memberRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 14,
    padding: "14px 16px",
    borderBottom: `1px solid ${uiTheme.colors.border}`,
  },
  memberCopy: {
    display: "grid",
    gap: 4,
  },
};




