import type { CSSProperties } from 'react';
import {
  controlBase,
  inputBase,
  pageActiveButtonBase,
  pageArrowBase,
  pageMain,
  paginationBase,
  primaryButtonBase,
  secondaryButtonBase,
  surfaceCard,
  uiTheme,
} from '../../theme/commonStyles';

export const styles: Record<string, CSSProperties> = {
  page: {
    ...pageMain,
    display: 'flex',
    flexDirection: 'column',
    gap: 22,
    backgroundImage:
      'linear-gradient(135deg, rgba(37, 99, 235, 0.07), transparent 30%), linear-gradient(225deg, rgba(15, 23, 42, 0.045), transparent 28%)',
  },
  topbarControls: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 18,
    marginTop: -12,
    marginBottom: 2,
  },
  headerSide: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 14,
    minWidth: 420,
  },
  metaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
  },
  metaChip: {
    ...controlBase,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    fontSize: 12,
    fontWeight: 500,
    color: uiTheme.colors.muted,
    borderRadius: 14,
  },
  searchWrap: {
    ...inputBase,
    width: '100%',
    maxWidth: 310,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    color: uiTheme.colors.muted,
    paddingLeft: 14,
    borderRadius: 14,
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    width: '100%',
    background: 'transparent',
    color: uiTheme.colors.text,
    fontSize: 14,
  },
  primaryButton: {
    ...primaryButtonBase,
    height: 42,
    padding: '0 18px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 600,
    borderRadius: 14,
  },
  secondaryButton: {
    ...secondaryButtonBase,
    height: 42,
    padding: '0 16px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 500,
    borderRadius: 14,
  },
  dangerButton: {
    ...secondaryButtonBase,
    height: 42,
    padding: '0 16px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 500,
    color: uiTheme.colors.danger,
    borderColor: '#fecaca',
    background: uiTheme.colors.dangerSoft,
    borderRadius: 14,
  },
  tabs: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    borderBottom: `1px solid ${uiTheme.colors.border}`,
  },
  tabButton: {
    border: 'none',
    background: 'transparent',
    color: uiTheme.colors.muted,
    fontWeight: 500,
    fontSize: 14,
    padding: '0 16px 14px',
    cursor: 'pointer',
  },
  tabActiveButton: {
    border: 'none',
    background: 'transparent',
    color: uiTheme.colors.primary,
    fontWeight: 600,
    fontSize: 14,
    padding: '0 16px 14px',
    cursor: 'pointer',
    boxShadow: `inset 0 -2px 0 ${uiTheme.colors.primary}`,
  },
  feedbackSuccess: {
    ...surfaceCard,
    borderColor: '#bbf7d0',
    background: uiTheme.colors.successSoft,
    color: uiTheme.colors.success,
    padding: '14px 18px',
    fontWeight: 500,
  },
  feedbackError: {
    ...surfaceCard,
    borderColor: '#fecaca',
    background: uiTheme.colors.dangerSoft,
    color: uiTheme.colors.danger,
    padding: '14px 18px',
    fontWeight: 500,
  },
  listCard: {
    ...surfaceCard,
    overflow: 'hidden',
    minHeight: 420,
    borderRadius: 20,
  },
  rows: {
    display: 'flex',
    flexDirection: 'column',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.3fr) minmax(320px, 0.7fr)',
    gap: 16,
    padding: '22px 20px',
    borderBottom: `1px solid ${uiTheme.colors.border}`,
    alignItems: 'center',
    cursor: 'pointer',
    background: uiTheme.colors.surface,
  },
  rowMain: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    minWidth: 0,
  },
  sectionIcon: {
    width: 66,
    height: 66,
    borderRadius: 18,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  rowCopy: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  rowTitle: {
    fontSize: 16,
  },
  rowDescription: {
    margin: 0,
    color: uiTheme.colors.muted,
    lineHeight: 1.45,
  },
  monitorBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    padding: '6px 10px',
    borderRadius: 999,
    background: uiTheme.colors.surfaceSoft,
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 500,
  },
  rowMetrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 16,
    alignItems: 'center',
  },
  metricBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  metricLabel: {
    fontSize: 12,
    color: uiTheme.colors.muted,
    fontWeight: 500,
  },
  metricValue: {
    fontSize: 16,
  },
  statusValue: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    fontWeight: 500,
  },
  statusDot: {
    fontSize: 13,
    lineHeight: 1,
  },
  statusGreen: {
    color: uiTheme.colors.success,
  },
  statusOrange: {
    color: uiTheme.colors.warning,
  },
  statusSlate: {
    color: uiTheme.colors.muted,
  },
  actionsWrap: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  moreButton: {
    ...controlBase,
    width: 42,
    height: 42,
    display: 'grid',
    placeItems: 'center',
    cursor: 'pointer',
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  menu: {
    ...surfaceCard,
    position: 'absolute',
    top: 48,
    right: 0,
    minWidth: 190,
    zIndex: 10,
    padding: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    borderRadius: 18,
  },
  menuItem: {
    border: 'none',
    background: 'transparent',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    borderRadius: 10,
    padding: '10px 12px',
    color: uiTheme.colors.text,
    cursor: 'pointer',
    fontWeight: 600,
  },
  menuItemDanger: {
    color: uiTheme.colors.danger,
  },
  emptyState: {
    minHeight: 420,
    display: 'grid',
    placeItems: 'center',
    textAlign: 'center',
    padding: '48px 20px',
    color: uiTheme.colors.text,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    margin: '0 auto 16px',
    display: 'grid',
    placeItems: 'center',
    background: uiTheme.colors.primarySoft,
    color: uiTheme.colors.primary,
  },
  emptyCopy: {
    margin: '10px 0 0',
    maxWidth: 440,
    color: uiTheme.colors.muted,
    lineHeight: 1.5,
  },
  emptyActions: {
    marginTop: 18,
    display: 'flex',
    justifyContent: 'center',
  },
  pagination: {
    ...paginationBase,
    padding: '20px 18px',
  },
  paginationText: {
    fontSize: 13,
  },
  pages: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  pageArrow: {
    ...pageArrowBase,
  },
  pageArrowLeft: {
    display: 'inline-flex',
    transform: 'rotate(180deg)',
  },
  pageActiveButton: {
    ...pageActiveButtonBase,
  },
  pageNumberButton: {
    ...pageArrowBase,
    width: 36,
    fontWeight: 500,
  },
  pageSize: {
    justifySelf: 'end',
    ...controlBase,
    padding: '8px 12px',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.38)',
    display: 'grid',
    placeItems: 'center',
    zIndex: 30,
    padding: 24,
    borderRadius: 20,
  },
  editorModal: {
    ...surfaceCard,
    width: 'min(880px, 100%)',
    maxHeight: '90vh',
    overflow: 'auto',
    padding: 24,
    borderRadius: 20,
  },
  manageModal: {
    ...surfaceCard,
    width: 'min(720px, 100%)',
    maxHeight: '85vh',
    overflow: 'auto',
    padding: 24,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 22,
  },
  modalTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
  },
  modalSubtitle: {
    margin: '8px 0 0',
    color: uiTheme.colors.muted,
  },
  modalClose: {
    ...controlBase,
    width: 38,
    height: 38,
    display: 'grid',
    placeItems: 'center',
    cursor: 'pointer',
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  formGrid: {
    display: 'grid',
    gap: 18,
  },
  field: {
    display: 'grid',
    gap: 10,
    fontWeight: 500,
    color: uiTheme.colors.text,
  },
  fieldHint: {
    margin: '-2px 0 0',
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 500,
  },
  fieldInput: {
    ...inputBase,
    height: 44,
    borderRadius: 14,
  },
  scheduleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
  },
  switchCard: {
    ...surfaceCard,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '0 12px',
    fontSize: 13,
  },
  textarea: {
    ...controlBase,
    minHeight: 110,
    padding: 14,
    resize: 'vertical',
    font: 'inherit',
    color: uiTheme.colors.text,
    borderRadius: 14,
  },
  iconPicker: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))',
    gap: 10,
  },
  iconOption: {
    ...controlBase,
    minHeight: 84,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 500,
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  iconOptionActive: {
    borderColor: uiTheme.colors.primary,
    boxShadow: `0 0 0 1px ${uiTheme.colors.primary}`,
    background: uiTheme.colors.primarySoft,
  },
  iconOptionBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    display: 'grid',
    placeItems: 'center',
  },
  monitorSelector: {
    ...controlBase,
    maxHeight: 280,
    overflow: 'auto',
    padding: 8,
    display: 'grid',
    gap: 8,
  },
  inlineSearchWrap: {
    ...inputBase,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 12,
    borderRadius: 12,
    color: uiTheme.colors.muted,
  },
  inlineSearchInput: {
    border: 'none',
    outline: 'none',
    width: '100%',
    minHeight: 40,
    background: 'transparent',
    color: uiTheme.colors.text,
    fontSize: 14,
  },
  monitorOption: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 12,
    background: uiTheme.colors.background,
  },
  selectorOptionSelected: {
    background: uiTheme.colors.surfaceSoft,
    color: uiTheme.colors.muted,
  },
  monitorOptionCopy: {
    minWidth: 0,
    display: 'grid',
    gap: 4,
  },
  monitorLinkedSection: {
    color: uiTheme.colors.primary,
    fontSize: 12,
    fontWeight: 500,
  },
  selectorEmpty: {
    padding: '18px 14px',
    textAlign: 'center',
    color: uiTheme.colors.muted,
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 22,
  },
  manageList: {
    display: 'grid',
    gap: 10,
  },
  manageRow: {
    ...surfaceCard,
    padding: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  manageRowMain: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
  },
  manageDescription: {
    margin: '6px 0 0',
    color: uiTheme.colors.muted,
  },
  manageActions: {
    display: 'flex',
    gap: 10,
  },
  inlineBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
  },
  inlineBadgeSuccess: {
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  inlineBadgeDanger: {
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  inlineBadgeSlate: {
    color: uiTheme.colors.muted,
    background: uiTheme.colors.surfaceSoft,
  },
};
