import type { CSSProperties } from 'react';
import {
  controlBase,
  inputBase,
  primaryButtonBase,
  secondaryButtonBase,
  surfaceCard,
  uiTheme,
} from '../../theme/commonStyles';

export const styles: Record<string, CSSProperties> = {
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15, 23, 42, 0.38)',
    display: 'grid',
    placeItems: 'center',
    zIndex: 30,
    padding: 24,
    borderRadius: 20,
  },
  editorModal: {
    ...surfaceCard,
    width: 'min(880px, 100%)',
    maxHeight: '90vh',
    overflow: 'auto',
    padding: 24,
    borderRadius: 20,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 22,
  },
  modalTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
  },
  modalSubtitle: {
    margin: '8px 0 0',
    color: uiTheme.colors.muted,
  },
  modalClose: {
    ...controlBase,
    width: 38,
    height: 38,
    display: 'grid',
    placeItems: 'center',
    cursor: 'pointer',
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  formGrid: {
    display: 'grid',
    gap: 18,
  },
  field: {
    display: 'grid',
    gap: 10,
    fontWeight: 500,
    color: uiTheme.colors.text,
  },
  fieldHint: {
    margin: '-2px 0 0',
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 500,
  },
  fieldInput: {
    ...inputBase,
    height: 44,
    borderRadius: 14,
  },
  scheduleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
  },
  switchCard: {
    ...surfaceCard,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '0 12px',
    fontSize: 13,
  },
  textarea: {
    ...controlBase,
    minHeight: 110,
    padding: 14,
    resize: 'vertical',
    font: 'inherit',
    color: uiTheme.colors.text,
    borderRadius: 14,
  },
  iconPicker: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))',
    gap: 10,
  },
  iconOption: {
    ...controlBase,
    minHeight: 84,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 500,
    background: uiTheme.colors.surface,
    borderRadius: 14,
  },
  iconOptionActive: {
    borderColor: uiTheme.colors.primary,
    boxShadow: `0 0 0 1px ${uiTheme.colors.primary}`,
    background: uiTheme.colors.primarySoft,
  },
  iconOptionBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    display: 'grid',
    placeItems: 'center',
  },
  monitorSelector: {
    ...controlBase,
    maxHeight: 280,
    overflow: 'auto',
    padding: 8,
    display: 'grid',
    gap: 8,
  },
  inlineSearchWrap: {
    ...inputBase,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 12,
    borderRadius: 12,
    color: uiTheme.colors.muted,
  },
  inlineSearchInput: {
    border: 'none',
    outline: 'none',
    width: '100%',
    minHeight: 40,
    background: 'transparent',
    color: uiTheme.colors.text,
    fontSize: 14,
  },
  monitorOption: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 12,
    padding: '10px 12px',
    borderRadius: 12,
    background: uiTheme.colors.background,
  },
  selectorOptionSelected: {
    background: uiTheme.colors.surfaceSoft,
    color: uiTheme.colors.muted,
  },
  monitorOptionCopy: {
    minWidth: 0,
    display: 'grid',
    gap: 4,
  },
  monitorLinkedSection: {
    color: uiTheme.colors.primary,
    fontSize: 12,
    fontWeight: 500,
  },
  selectorEmpty: {
    padding: '18px 14px',
    textAlign: 'center',
    color: uiTheme.colors.muted,
  },
  feedbackError: {
    ...surfaceCard,
    borderColor: '#fecaca',
    background: uiTheme.colors.dangerSoft,
    color: uiTheme.colors.danger,
    padding: '14px 18px',
    fontWeight: 500,
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 22,
  },
  primaryButton: {
    ...primaryButtonBase,
    height: 42,
    padding: '0 18px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 600,
    borderRadius: 14,
  },
  secondaryButton: {
    ...secondaryButtonBase,
    height: 42,
    padding: '0 16px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    fontWeight: 500,
    borderRadius: 14,
  },
  inlineBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
  },
  inlineBadgeSuccess: {
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  inlineBadgeDanger: {
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  inlineBadgeSlate: {
    color: uiTheme.colors.muted,
    background: uiTheme.colors.surfaceSoft,
  },
};
