ALTER TYPE "MonitorType" ADD VALUE IF NOT EXISTS 'SSL';
ALTER TYPE "MonitorType" ADD VALUE IF NOT EXISTS 'TCP';
ALTER TYPE "MonitorType" ADD VALUE IF NOT EXISTS 'DNS';

ALTER TABLE "Monitor"
ADD COLUMN IF NOT EXISTS "tcpPort" INTEGER,
ADD COLUMN IF NOT EXISTS "keyword" TEXT,
ADD COLUMN IF NOT EXISTS "sslWarningDays" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN IF NOT EXISTS "dnsRecordType" TEXT NOT NULL DEFAULT 'A',
ADD COLUMN IF NOT EXISTS "dnsExpectedValue" TEXT;
