import type { CSSProperties } from 'react';
import {
  controlBase,
  filterGroupBase,
  inputBase,
  pageActiveButtonBase,
  pageArrowBase,
  paginationBase,
  secondaryButtonBase,
  surfaceCard,
  tableCardBase,
  toneStyles,
  uiTheme,
} from '../../theme/commonStyles';

export const styles: Record<string, CSSProperties> = {
  card: {
    ...tableCardBase,
    display: "grid",
    gap: 22,
    width: "100%",
    padding: 28,
    overflow: "hidden",
    borderRadius: uiTheme.radii.md,
  },
  filters: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "flex-end",
  },
  search: {
    ...inputBase,
    minWidth: 240,
    flex: "1 1 260px",
  },
  filterGroup: {
    ...filterGroupBase,
    minWidth: 148,
  },
  select: {
    ...inputBase,
    minWidth: 148,
  },
  secondaryButton: {
    ...secondaryButtonBase,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 42,
    padding: "0 16px",
    cursor: "pointer",
  },
  bulkToolbar: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
    borderRadius: uiTheme.radii.md,
    border: `1px solid ${uiTheme.colors.border}`,
    background: uiTheme.colors.surfaceSoft,
    padding: "14px 16px",
  },
  bulkTitle: {
    display: "block",
    marginBottom: 4,
    color: uiTheme.colors.text,
  },
  bulkCopy: {
    margin: 0,
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  bulkActions: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  dangerButton: {
    ...secondaryButtonBase,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 42,
    padding: "0 16px",
    cursor: "pointer",
    borderColor: uiTheme.colors.danger,
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  feedbackSuccess: {
    borderRadius: uiTheme.radii.md,
    border: `1px solid ${uiTheme.colors.success}`,
    background: toneStyles.green.background,
    color: toneStyles.green.color,
    padding: "12px 14px",
    fontSize: 14,
    fontWeight: 500,
  },
  feedbackError: {
    borderRadius: uiTheme.radii.md,
    border: `1px solid ${uiTheme.colors.danger}`,
    background: toneStyles.red.background,
    color: toneStyles.red.color,
    padding: "12px 14px",
    fontSize: 14,
    fontWeight: 500,
  },
  empty: {
    margin: 0,
    padding: "20px 0",
    color: uiTheme.colors.muted,
    textAlign: "center",
  },
  tableScroll: {
    width: "100%",
    overflowX: "auto",
    overflowY: "visible",
    paddingBottom: 2,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: 980,
  },
  th: {
    padding: "0 20px 16px",
    textAlign: "left",
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 600,
  },
  thActions: {
    padding: "0 12px 16px 20px",
    textAlign: "right",
    color: uiTheme.colors.muted,
    fontSize: 12,
    fontWeight: 600,
  },
  checkboxHeader: {
    width: 52,
    padding: "0 16px 16px 0",
    textAlign: "center",
  },
  tr: {
    borderTop: `1px solid ${uiTheme.colors.border}`,
    transition: "background 160ms ease, box-shadow 160ms ease",
    cursor: "pointer",
  },
  trHover: {
    background: uiTheme.colors.surfaceSoft,
  },
  trSelected: {
    background: `${uiTheme.colors.primarySoft}`,
  },
  td: {
    padding: "18px 20px",
    color: uiTheme.colors.text,
    verticalAlign: "middle",
  },
  tdActions: {
    padding: "18px 12px 18px 20px",
    verticalAlign: "middle",
    textAlign: "right",
  },
  checkboxCell: {
    padding: "18px 16px 18px 0",
    textAlign: "center",
    verticalAlign: "middle",
  },
  webCell: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  webIcon: {
    ...controlBase,
    width: 36,
    height: 36,
    display: "grid",
    placeItems: "center",
    color: uiTheme.colors.primary,
    background: uiTheme.colors.primarySoft,
    flexShrink: 0,
  },
  monitorName: {
    display: "block",
    marginBottom: 4,
  },
  url: {
    color: uiTheme.colors.muted,
    fontSize: 13,
    wordBreak: "break-word",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 12,
    fontWeight: 600,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    background: "currentColor",
  },
  uptimeCell: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  alertBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 28,
    minHeight: 28,
    padding: "0 10px",
    borderRadius: 999,
    background: toneStyles.slate.background,
    color: toneStyles.slate.color,
    fontSize: 12,
    fontWeight: 700,
  },
  alertBadgeDanger: {
    background: toneStyles.red.background,
    color: toneStyles.red.color,
  },
  actions: {
    position: "relative",
    display: "inline-flex",
    justifyContent: "flex-end",
  },
  actionButton: {
    ...controlBase,
    width: 34,
    height: 34,
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
  },
  actionMenu: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 5,
    minWidth: 220,
    display: "grid",
    gap: 4,
    padding: 8,
    borderRadius: uiTheme.radii.md,
    border: `1px solid ${uiTheme.colors.border}`,
    background: uiTheme.colors.surface,
    boxShadow: "0 18px 38px rgba(15, 23, 42, 0.12)",
  },
  actionMenuItem: {
    ...secondaryButtonBase,
    width: "100%",
    justifyContent: "flex-start",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minHeight: 40,
    padding: "0 12px",
    cursor: "pointer",
    background: "transparent",
    borderColor: "transparent",
  },
  pagination: {
    ...paginationBase,
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
    alignItems: "center",
  },
  paginationText: {
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  pages: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  pageArrow: {
    ...pageArrowBase,
  },
  pageArrowLeft: {
    display: "inline-flex",
    transform: "rotate(180deg)",
  },
  pageNumberButton: {
    ...controlBase,
    minWidth: 36,
    height: 36,
    cursor: "pointer",
  },
  pageActiveButton: {
    ...pageActiveButtonBase,
    minWidth: 36,
    height: 36,
    cursor: "pointer",
  },
  pageSizeWrap: {
    display: "flex",
    justifyContent: "flex-end",
    minWidth: 120,
  },
  pageSizeText: {
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "grid",
    placeItems: "center",
    padding: 20,
    background: "rgba(15, 23, 42, 0.45)",
  },
  confirmModal: {
    ...surfaceCard,
    width: "min(520px, 100%)",
    display: "grid",
    gap: 18,
    padding: 24,
  },
  confirmIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 999,
    display: "grid",
    placeItems: "center",
    background: uiTheme.colors.dangerSoft,
    color: uiTheme.colors.danger,
  },
  confirmTitle: {
    margin: 0,
    fontSize: 22,
  },
  confirmCopy: {
    margin: 0,
    color: uiTheme.colors.muted,
    lineHeight: 1.5,
  },
  confirmList: {
    display: "grid",
    gap: 10,
  },
  confirmListItem: {
    display: "grid",
    gap: 2,
    borderRadius: uiTheme.radii.sm,
    background: uiTheme.colors.surfaceSoft,
    padding: "12px 14px",
  },
  confirmListUrl: {
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  confirmListMore: {
    color: uiTheme.colors.muted,
    fontSize: 13,
  },
  confirmActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 12,
    flexWrap: "wrap",
  },
};
