import type { CSSProperties } from 'react';
import {
  controlBase,
  filterGroupBase,
  inputBase,
  kpiCardBase,
  pageActiveButtonBase,
  pageArrowBase,
  pageMain,
  paginationBase,
  selectFakeBase,
  surfaceCard,
  tableCardBase,
  uiTheme,
} from '../../theme/commonStyles';

export const styles: Record<string, CSSProperties> = {
  main: {
    ...pageMain,
    overflow: 'auto',
    backgroundImage:
      'linear-gradient(135deg, rgba(37, 99, 235, 0.07), transparent 30%), linear-gradient(225deg, rgba(15, 23, 42, 0.045), transparent 28%)',
  },

  kpiGrid: { display: 'grid', gridTemplateColumns: 'repeat(5, minmax(0, 1fr))', gap: 14, marginBottom: 14 },
  kpiCard: { ...kpiCardBase, padding: 18, display: 'flex', gap: 14, alignItems: 'center', minHeight: 94, borderRadius: 20 },
  kpiIcon: { width: 48, height: 48, borderRadius: 16, display: 'grid', placeItems: 'center', flexShrink: 0 },
  kpiTitle: { margin: 0, color: uiTheme.colors.text, fontWeight: 600, fontSize: 13 },
  kpiValue: { display: 'block', marginTop: 6, fontSize: 24, lineHeight: 1 },

  contentGrid: { display: 'grid', gridTemplateColumns: '1fr 300px', gap: 14, alignItems: 'start' },
  tableCard: {
    ...tableCardBase,
    borderRadius: 20,
    padding: 20,
    alignSelf: 'start',
    height: 'fit-content',
    background: uiTheme.colors.surface,
  },
  toolbar: {
    display: 'grid',
    gridTemplateColumns: 'minmax(260px, 2fr) minmax(180px, 1fr) minmax(240px, 1.5fr)',
    alignItems: 'end',
    gap: 12,
    marginBottom: 18,
    width: '100%',
  },
  search: { ...inputBase, borderRadius: 14, width: '100%' },
  select: { ...inputBase, borderRadius: 14, width: '100%' },
  filterGroup: { ...filterGroupBase, width: '100%' },
  tabs: { display: 'flex', gap: 8, alignItems: 'center', width: '100%' },
  tabButton: {
    ...controlBase,
    borderRadius: 14,
    padding: '0 14px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 13,
    height: 40,
    display: 'inline-flex',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  tabActive: { background: uiTheme.colors.primarySoft, borderColor: uiTheme.colors.primaryLight, color: uiTheme.colors.primary },
  table: { width: '100%', borderCollapse: 'separate', borderSpacing: 0 },
  th: { textAlign: 'left', padding: '13px 10px', color: uiTheme.colors.muted, fontSize: 12, borderBottom: `1px solid ${uiTheme.colors.border}`, fontWeight: 700 },
  tr: { borderBottom: `1px solid ${uiTheme.colors.surfaceSoft}`, background: uiTheme.colors.surface, cursor: 'pointer' },
  trHover: { background: uiTheme.colors.surfaceSoft },
  td: { padding: '14px 10px', fontSize: 12, color: uiTheme.colors.text },
  url: { marginTop: 3, color: uiTheme.colors.muted, fontSize: 11 },
  badge: { padding: '5px 9px', borderRadius: 999, fontSize: 11, fontWeight: 600, whiteSpace: 'nowrap', display: 'inline-flex', alignItems: 'center', gap: 6 },
  badgeDot: { width: 7, height: 7, borderRadius: 999, background: 'currentColor', display: 'inline-block' },
  empty: { color: uiTheme.colors.muted, fontSize: 13 },
  pagination: { ...paginationBase, padding: '16px 20px' },
  pages: { display: 'flex', gap: 10, alignItems: 'center', justifySelf: 'center', color: uiTheme.colors.text },
  pageActiveButton: pageActiveButtonBase,
  pageNumberButton: { border: '1px solid transparent', background: 'transparent', color: uiTheme.colors.muted, minWidth: 36, textAlign: 'center', cursor: 'pointer', padding: '7px 11px' },
  pageArrow: pageArrowBase,
  pageArrowLeft: { transform: 'rotate(180deg)', display: 'grid', placeItems: 'center' },
  selectFake: { ...selectFakeBase, justifySelf: 'end' },

  sidePanel: { display: 'flex', flexDirection: 'column', gap: 14 },
  sideCard: { ...surfaceCard, borderRadius: 20, padding: 20 },
  cardTitle: { margin: 0, fontSize: 16, fontWeight: 700 },
  donut: { width: 130, height: 130, borderRadius: '50%', margin: '24px auto', display: 'grid', placeItems: 'center', boxShadow: 'inset 0 0 0 1px rgba(15, 23, 42, 0.05)' },
  donutInner: { width: 88, height: 88, borderRadius: '50%', background: uiTheme.colors.surface, display: 'grid', placeItems: 'center', textAlign: 'center', fontSize: 12, boxShadow: `0 0 0 6px ${uiTheme.colors.surfaceSoft}` },
  legendRow: { display: 'grid', gridTemplateColumns: '14px 1fr 32px', gap: 8, alignItems: 'center', fontSize: 12, padding: '8px 0', borderTop: `1px solid ${uiTheme.colors.surfaceSoft}` },
  dot: { width: 8, height: 8, borderRadius: 999 },
  topRow: { display: 'grid', gridTemplateColumns: '20px 1fr 28px', alignItems: 'center', gap: 8, padding: '9px 0', fontSize: 12 },
  countBadge: { background: uiTheme.colors.dangerSoft, color: uiTheme.colors.danger, borderRadius: 999, padding: '3px 8px', fontWeight: 800 },
  notificationsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  linkButton: {
    border: 0,
    background: 'transparent',
    color: uiTheme.colors.primary,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 700,
    padding: 0,
  },
  notificationsList: {
    display: 'grid',
    gap: 10,
  },
  notificationItem: {
    width: '100%',
    border: 0,
    background: 'transparent',
    display: 'grid',
    gridTemplateColumns: '30px 1fr',
    alignItems: 'center',
    gap: 10,
    padding: '10px 0',
    color: uiTheme.colors.text,
    cursor: 'pointer',
    textAlign: 'left',
    borderTop: `1px solid ${uiTheme.colors.surfaceSoft}`,
  },
  notificationItemUnread: {
    color: uiTheme.colors.primary,
  },
  notificationIconDanger: {
    width: 30,
    height: 30,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.danger,
    background: uiTheme.colors.dangerSoft,
  },
  notificationIconSuccess: {
    width: 30,
    height: 30,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 999,
    color: uiTheme.colors.success,
    background: uiTheme.colors.successSoft,
  },
  notificationCopy: {
    display: 'grid',
    gap: 3,
    minWidth: 0,
  },
};

